### ISSUE TITLE
ConfigurationError: Could not find name 'devtest.sandiegodata.org' in group 'accounts'.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/ambry#40]
```bash
python -m unittest test_library.Test.test_s3_push
```
http://pastebin.com/6TJ4uUFa

It seems I need access and secret for devtest.sandiegodata.org , but do we really need to use remote servers for testing? I think it should be replaced with local data (or mocked if there is not way to use local data).

**Comment by ericbusboom** [comment]
Well, if we're going to push to S3, there should probably be a test that actually pushes to S3. But, the cache code has moved to the ckcache package, so maybe it would be better to test it there. 

The easiest way to solve the problem is make the s3-remote not have a remote cache URL. SO, in test/bundles/testbundle/library-test-config.yaml, change

```

    s3-remoted:
      remotes:
        - 's3://devtest.sandiegodata.org/s3-remote#compress'
```

To a reference to  a local file, like 

```

    s3-remoted:
      remotes:
        - '{root}/mock-s3-remote'
```
